
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Scrollbar, Frame
import os


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\KENNARD\lomba\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def configure_scroll_region(event):
    canvas.config(scrollregion=canvas.bbox("all"))

def open_main_window_2():
    # Destroy the current window to avoid overlapping windows
    window.destroy()

    # Run main.py to open the next window (assuming main.py is a separate file)
    os.system("python artikel2.py")

def open_main_window_3():
    # Destroy the current window to avoid overlapping windows
    window.destroy()

    # Run main.py to open the next window (assuming main.py is a separate file)
    os.system("python artikel3.py")

def open_main_window_5():
    # Destroy the current window to avoid overlapping windows
    window.destroy()

    # Run main.py to open the next window (assuming main.py is a separate file)
    os.system("python artikel5.py")

def open_main_window_6():
    # Destroy the current window to avoid overlapping windows
    window.destroy()

    # Run main.py to open the next window (assuming main.py is a separate file)
    os.system("python artikel6.py")

def open_main_window_7():
    # Destroy the current window to avoid overlapping windows
    window.destroy()

    # Run main.py to open the next window (assuming main.py is a separate file)
    os.system("python artikel7.py")

def open_main_window_8():
    # Destroy the current window to avoid overlapping windows
    window.destroy()

    # Run main.py to open the next window (assuming main.py is a separate file)
    os.system("python artikel8.py")

def open_main_window_9():
    # Destroy the current window to avoid overlapping windows
    window.destroy()

    # Run main.py to open the next window (assuming main.py is a separate file)
    os.system("python artikel9.py")



window = Tk()

window.geometry("1200x800")
window.configure(bg = "#E0E0E0")


canvas = Canvas(
    window,
    bg = "#E0E0E0",
    height = 800,
    width = 1200,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)


canvas.place(x = 0, y = 0)

vertical_scrollbar = Scrollbar(window, orient="vertical", command=canvas.yview)
vertical_scrollbar.pack(side="right", fill="y")

canvas.config(yscrollcommand=vertical_scrollbar.set)
canvas.pack(side="left", fill="both", expand=True)

scrollable_frame = Frame(canvas, bg="#E0E0E0")
scrollable_frame.bind("<Configure>", configure_scroll_region)

frame_window = canvas.create_window((0, 0), window=scrollable_frame, anchor="nw")


button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=450.0,
    y=332.0,
    width=300.0,
    height=220.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=open_main_window_2,
    relief="flat"
)
button_2.place(
    x=831.0,
    y=334.0,
    width=300.0,
    height=220.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=open_main_window_3,
    relief="flat"
)
button_3.place(
    x=69.0,
    y=334.0,
    width=300.0,
    height=220.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=69.0,
    y=571.0,
    width=300.0,
    height=220.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=open_main_window_5,
    relief="flat"
)
button_5.place(
    x=450.0,
    y=571.0,
    width=300.0,
    height=220.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=open_main_window_6,
    relief="flat"
)
button_6.place(
    x=831.0,
    y=571.0,
    width=300.0,
    height=220.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=open_main_window_7,
    relief="flat"
)
button_7.place(
    x=450.0,
    y=92.0,
    width=300.0,
    height=217.16738891601562
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=open_main_window_8,
    relief="flat"
)
button_8.place(
    x=831.0,
    y=92.0,
    width=300.0,
    height=233.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=open_main_window_9,
    relief="flat"
)
button_9.place(
    x=69.0,
    y=92.0,
    width=300.0,
    height=220.0
)

canvas.create_rectangle(
    0.0,
    0.0,
    1200.0,
    70.0,
    fill="#000000",
    outline="")

canvas.create_text(
    460.0,
    16.0,
    anchor="nw",
    text="Indonesian Journal",
    fill="#FFFFFF",
    font=("Inter Light", 32 * -1)
)
window.resizable(False, False)
window.mainloop()
